# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jikun Li
description: A pure mathematics student
baseurl: "/bay"
url: "https://jikun-li.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: jakelee191210@gmail.com
    - type: Wechat
      value: 1239841953
      link: "#"
 # follow:
 #   - type: twitter
 #    name: Twitter
 #     link: http://twitter.com/YourTwitterUsername
 #     username: "@YourTwitterUsername"

 #  - type: github
 #     name: GitHub
 #     link: http://github.com/YourGitHubUsername 


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
